### ISSUE TITLE
System Error: 0x00000002: The system cannot find the file specified

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/io_texture_VTF#5]
Blender 2.80 Beta (Date: 2019-02-10 Hash: 0b6dbbc306b0)
io_texture_VTF: v2.0 (d1adf64 13 hours ago)
SFM Model (NSFW): https://sfmlab.com/item/2711/
This is the same model from the demo I made: https://gfycat.com/glumopenalaskajingle

When attempting to import the VTF textures, I get the following error:

---------------------------------------
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_texture_VTF-blender280\__init__.py", line 51, in execute
    VTF.import_texture(str(directory / file.name), self.load_alpha, self.only_alpha)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_texture_VTF-blender280\VTF.py", line 23, in import_texture
    raise Exception("Failed to load texture :{}".format(vtf_lib.get_last_error()))
Exception: Failed to load texture :Error:
Error opening file.

System Error: 0x00000002:
The system cannot find the file specified.

location: <unknown location>:-1

------------------------------------------
Is there a proper way to paste code here? 
The code tag doesn't seem to acknowledge the content between angle brackets <>

**Comment by Gnates** [comment]
Sorry for the delay.
I usually install Blender 2.80 Beta builds on the weekends.
It looks like one of the 2.80 Beta builds from the previous weekend had a minor issue.

The issue is no longer present in yesterday's build:
Blender 2.80 Beta (Date: 2019-02-19 Hash: 790cb7799dcf)
io_texture_VTF: v2.0 ( d1adf64 )

Also, heads-up, it looks like the Blender developers are discussing possible 2nd redesign of the Outliner and Collections system.
