### ISSUE TITLE
io_texture_VTF add-on activation error: No module named 'io_texture_VTF.vtf

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/io_texture_VTF#7]
**Blender 2.80 Beta** [ Date: **2019-03-03** Hash: **ae977d13f8e9** ]
io_texture_VTF **v2.0** https://github.com/REDxEYE/io_texture_VTF/releases/download/2.0/io_texture_VTF.zip
9465544

Installation had no errors.
Activating the add-on produced the error message below:

Traceback (most recent call last):
  File "D:\Blender\Blender2-8\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_texture_VTF\__init__.py", line 2, in <module>
    from .vtf import import_texture, export_texture
ModuleNotFoundError: No module named 'io_texture_VTF.vtf'

**Comment by green-s** [comment]
The zip doesn't include the submodules. `git clone --recursive https://github.com/REDxEYE/io_texture_VTF`, then put a build of VTFLib in VTFLibWrapper (named `VTFLib.x64.dll` for x64, `VTFLib.x86.dll` for x86).

**Comment by yasmeenel3sh** [comment]
It says access denied

**Comment by ZenkakuHiragana** [comment]
I did the following steps and it seems I could successfully activate the addon:

- Worked on Blender 4.0, Windows 11
- Locate the files extracted by Blender when installing
  - for me, it was `C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_texture_VTF`
- Rename `VTF.py` to `vtf.py` and `VTFWrapper` to `VTFLibWrapper`

**Comment by Dushess** [comment]
And then it creates an error while importing both texture and material. I may be foolish with this, but this is the problem: 
![image](https://github.com/REDxEYE/io_texture_VTF/assets/15954961/34140989-224b-4b43-a86a-90b326b1b527)

**Comment by REDxEYE** [comment]
Why are you using this addon instead of SourceIO?
